#!/bin/bash

#Copyright (C) 2013 Robin McCorkell

#This file is part of Karoshi Client.
#
#Karoshi Client is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Client is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Client.  If not, see <http://www.gnu.org/licenses/>.

#The Karoshi Team can be contacted either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

function sendXNotifications {
	while read DISPLAY; do
		export DISPLAY
		if ! xhost; then
			#We don't have permission yet
			export XAUTHORITY=`ps aux | grep -- ' -auth ' | grep -- " $DISPLAY" | sed 's/.*-auth \([^ ]*\).*/\1/'`
			if ! xhost; then continue; fi #We STILL don't have any permission, so just ignore
		fi
		#At this point we should have permission to write to the display
		notify-send -u critical "Scheduled Shutdown" "This system is going down in $1 minute/s\nMake sure to save your work!" -i /opt/karoshi/linuxclientsetup/images/smalllogo.xpm
		#Reset variables
		unset DISPLAY
		unset XAUTHORITY
	done < <(grep -hz "^DISPLAY=" /proc/*/environ | tr \\0 \\n | sed 's/^DISPLAY=\([^\.]*\).*/\1/' | sort -u)
}

#start shutdown sequence
shutdown -h +5 &

#send 5 minute notification
sendXNotifications 5
#wait for 4 minutes
sleep 240
#send 1 minute notification
sendXNotifications 1
