#!/bin/bash

#Clear Trash folder
[ -d ~/.local/share/Trash ] && rm -rf ~/.local/share/Trash

[ -d ~/network/home ] || exit
#Everything below this point requires ~/network/home to exist

#####################
#Backup configuration
#####################
function checkAndList {
	if [ -e ~/"$1" ]; then LIST=( "${LIST[@]}" "$1" ); fi
}

#Create list of files
#checkAndList .config/dconf/user
#checkAndList .config/libreoffice/3/user/config/wordbook/
#checkAndList .config/Thunar/thunarrc
#checkAndList .config/Terminal/terminalrc
#checkAndList .local/share/recently-used.xbel
#checkAndList .mozilla/firefox/jzlvae43.default/places.sqlite
#checkAndList .rednotebook/
#checkAndList .bash_history
#checkAndList .bashrc
#checkAndList .bash_profile
#checkAndList .bash_logout
#checkAndList .codeblocks/
#checkAndList .eclipse/
#checkAndList .greenfoot/
#checkAndList .netbeans/
#checkAndList .wireshark/

#Create archive in ~/network/home/.configuration.tar.gz
[ -f ~/network/home/.configuration.tar.gz ] && rm ~/network/home/.configuration.tar.gz
#[[ "${LIST[@]}" ]] && tar -cz -C ~ -f ~/network/home/.configuration.tar.gz "${LIST[@]}"

LIST=( )
while read -d $'\0' -r file ; do
	checkAndList "${file##~/}"
done < <(find ~ -mindepth 1 -maxdepth 1 -xdev -not '(' -name '.mozilla' -o -name '.cache' -o -name '.thumbnails' -o -name '.Xauthority' -o -name '.ICEauthority' -o -name '.xsession-errors' -o -name '.pulse*' -o -name '.gvfs' -o -name '.dbus' -o -name '.gtk-bookmarks' -o -name '.VirtualBox' -o -name '.rednotebook' ')' -name '.*' -print0)
checkAndList .mozilla/firefox/jzlvae43.default/places.sqlite

[[ "${LIST[@]}" ]] && tar -cz --one-file-system -C ~ -f ~/network/home/.configuration.tar.gz "${LIST[@]}"

#####################
#Backup desktop files
#####################
LIST=( )
while read -d $'\0' -r file ; do
	checkAndList "${file##~/}"
done < <(find ~/Desktop -mindepth 1 -maxdepth 1 -not -name "karoshi-*.desktop" -and -size -1024c -print0)

#Create archive in ~/network/home/.desktop-icons.tar.gz
[ -f ~/network/home/.desktop-icons.tar.gz ] && rm ~/network/home/.desktop-icons.tar.gz
[[ "${LIST[@]}" ]] && tar -cz --one-file-system -C ~ -f ~/network/home/.desktop-icons.tar.gz "${LIST[@]}"
