#!/bin/bash

#Copyright (C) 2013 Robin McCorkell

#This file is part of Karoshi Client.
#
#Karoshi Client is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Client is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Client.  If not, see <http://www.gnu.org/licenses/>.

#The Karoshi Team can be contacted either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

if [[ ! $PAM_USER ]]; then
	echo "ERROR: Must be run through pam_exec.so" >&2
	exit $PAM_CRED_UNAVAIL
fi
#Make sure the user exists
if ! getent passwd "$PAM_USER" >/dev/null; then
	echo "ERROR: Must be run with a valid PAM_USER" >&2
	exit $PAM_USER_UNKNOWN
fi

user_info=$(getent passwd "$PAM_USER")
user_uid=$(cut -d":" -f3 <<< "$user_info")
user_gid=$(cut -d":" -f4 <<< "$user_info")
user_home=$(cut -d":" -f6 <<< "$user_info")

if ! [[ $user_uid -ge 1000 ]]; then
	echo "User is not a domain user - exiting"
	exit $PAM_IGNORE
fi

if [[ $user_home != /home/* ]]; then
	echo "User does not have a home area in /home - exiting"
	exit $PAM_IGNORE
fi

if [[ -d $user_home ]]; then
	echo "Removing home directory: $user_home"
	if ! rm -rf --one-file-system "$user_home"; then
		echo "ERROR: Problem with removing home directory" >&2
		exit $PAM_SYSTEM_ERR
	fi
	exit $PAM_SUCCESS
else
	exit $PAM_IGNORE
fi

