#!/bin/bash

#Copyright (C) 2013 Robin McCorkell

#This file is part of Karoshi Client.
#
#Karoshi Client is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Client is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Client.  If not, see <http://www.gnu.org/licenses/>.

#The Karoshi Team can be contacted either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

source /opt/karoshi/linuxclientsetup/utilities/pam-common

if [[ ! $PAM_USER ]]; then
	echo "ERROR: Must be run through pam_exec.so" >&2
	exit $PAM_CRED_UNAVAIL
fi
#Make sure the user exists
if ! getent passwd "$PAM_USER" >/dev/null; then
	echo "ERROR: Must be run with a valid PAM_USER" >&2
	exit $PAM_USER_UNKNOWN
fi

if [[ -f /opt/karoshi/paths ]]; then
	source /opt/karoshi/paths
else
	source /opt/karoshi/linuxclientsetup/paths
fi

#Check for required directories
if [[ ! -d $KAROSHI_DATA ]]; then
	echo "ERROR: Missing $KAROSHI_DATA" >&2
	exit $PAM_SYSTEM_ERR
fi
if [[ ! -w $KAROSHI_DATA ]]; then
	exit $PAM_PERM_DENIED
fi
if [[ ! -d $KAROSHI_DATA/$KAROSHI_VIRTUALBOX ]]; then
	echo "$KAROSHI_DATA/$KAROSHI_VIRTUALBOX did not exist - creating"
	mkdir "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX" -m 0755
fi

if [[ ! -d $KAROSHI_DATA/$KAROSHI_VIRTUALBOX/isos ]]; then
	echo "$KAROSHI_DATA/$KAROSHI_VIRTUALBOX/isos did not exist - creating"
	mkdir "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/isos -m 1777
fi
if [[ ! -d $KAROSHI_DATA/$KAROSHI_VIRTUALBOX/users ]]; then
	echo "$KAROSHI_DATA/$KAROSHI_VIRTUALBOX/users did not exist - creating"
	mkdir "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/users -m 0755
fi

if ! [[ $USER_UID -ge 1000 ]]; then
	echo "User is not a domain user - exiting"
	exit $PAM_IGNORE
fi

function make_virtualbox_dir {
	echo "Creating user folder: '$KAROSHI_DATA/$KAROSHI_VIRTUALBOX/users/$PAM_USER'"
	mkdir "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/users/"$PAM_USER" -m 0700
	chown $USER_UID:$USER_GID "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/users/"$PAM_USER"
}

if [[ ! -d $KAROSHI_DATA/$KAROSHI_VIRTUALBOX/users/$PAM_USER ]]; then
	make_virtualbox_dir
fi

folder_owner=$(stat -c %U "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/users/"$PAM_USER")
if [[ $folder_owner != $PAM_USER ]]; then
	echo "Incorrect owner of user folder: $folder_owner"
	echo "Moving '$KAROSHI_DATA/$KAROSHI_VIRTUALBOX/users/$PAM_USER' to '$KAROSHI_DATA/$KAROSHI_VIRTUALBOX/users/$PAM_USER.old'"
	[[ -e $KAROSHI_DATA/$KAROSHI_VIRTUALBOX/users/$PAM_USER.old ]] && rm -rf "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/users/"$PAM_USER".old
	mv "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/users/"$PAM_USER" "$KAROSHI_DATA"/"$KAROSHI_VIRTUALBOX"/users/"$PAM_USER".old
	make_virtualbox_dir
fi

exit $PAM_SUCCESS
