#!/bin/bash

mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts
export HOME=/root
export LC_ALL=C

#Create /tmp/fake for symlinks to /bin/true
mkdir /tmp/fake

ln -s /bin/true /tmp/fake/initctl
ln -s /bin/true /tmp/fake/invoke-rc.d
ln -s /bin/true /tmp/fake/restart
ln -s /bin/true /tmp/fake/start
ln -s /bin/true /tmp/fake/stop
ln -s /bin/true /tmp/fake/start-stop-daemon
ln -s /bin/true /tmp/fake/service

export PATH=/tmp/fake:$PATH
export DEBIAN_FRONTEND=noninteractive

# Update package sources, this should also gather the GPG keys from the PPAs,
# just in case the keys are added later in the script.
echo -e "\nChroot: updating apt for wget installation\n"
echo -e "\nExpect gpg errors as the keys have not been added yet!"
sleep 4
apt-get update

# Required for wget keys
echo -e "\nChroot: Installing wget\n"
apt-get install -y wget

# Add GPG keys in-case they were not gathered already
echo -e "\nChroot: Adding GPG keys for package sources.\n"
# download.virtualbox.org/virtualbox/
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | apt-key add -
# otto-kesselgulasch/gimp/
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 614C4B38
# mirrors.coreix.net/mariadb/
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xcbcb082a1bb943db
# ppa.launchpad.net/libreoffice/
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1378B444
# ppa.launchpad.net/nilarimogard/webupd8/
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4C9D234C
# ppa.launchpad.net/webupd8team/y-ppa-manager/
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
# ppa.launchpad.net/ubuntu-wine/ppa/
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F9CB8DB0
# ppa.launchpad.net/gottcode/gcppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 58043CFF
# ppa.launchpad.net/catfish-search/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9163B46D
# ppa.launchpad.net/mozillateam/thunderbird-next
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE49EC21
# wireshark-dev/stable
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14ECA0F0
# ppa.launchpad.net/stellarium/stellarium-releases
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C68D72A5
# ppa.launchpad.net/kubuntu-ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8AC93F7A
# ppa.launchpad.net/suraia/server
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1D9D38E5
# ppa.launchpad.net/scribus
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 64B6EE15
# ppa.launchpad.net/inkscape.dev/stable
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B9A06DE3
# ppa.launchpad.net/dobey/audiotools
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AD555F67
# ppa.launchpad.net/ubuntuhandbook1/audacity
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 852541CB
# ppa.launchpad.net/mscore-ubuntu/mscore-stable
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3A258030
# ppa.launchpad.net/openshot.developers/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B9BA26FA
# ppa.launchpad.net/videolan/stable-daily
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 801DF724
# ppa.launchpad.net/pasgui/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F599ACE3
# ppa.launchpad.net/vajdics/netbeans-installer
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 21B4A5B3
# ppa.launchpad.net/git-core/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E1DF1F24
# ppa.launchpad.net/xenopathic/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 96EFFE86
# ppa.launchpad.net/xubuntu-dev/xfce-4.12
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 142986CE
# ppa.launchpad.net/light-locker/release
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 413214C1
# ppa.launchpad.net/kxstudio-team/hydrogen
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DF8063EB
# ppa.launchpad.net/ubuntu-audio-dev/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B194E5
# ppa.launchpad.net/renbag/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4A346C04
# ppa.launchpad.net/rebuntu16/glade-3.19+-trust
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 98F78EB3
# packagecloud.io/github/git-lfs
wget -q -O- https://packagecloud.io/github/git-lfs/gpgkey | apt-key add -
# archive.getdeb.net/ubuntu
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | apt-key add -
# archive.getdeb.net - bluegriffon
wget -q http://archive.getdeb.net/getdeb-archive.key -O- | apt-key add -
# ppa.launchpad.net/mozillateam/xul-ext
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE49EC21
#### ppa.launchpad.net/webupd8team/java
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
#### ppa.launchpad.net/numix/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0F164EEB
#### ppa.launchpad.net/openjdk/ppa
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 214AEA0E

# unknown/to be labeled
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 614C4B28
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
apt-key adv --keyserver keys.gnupg.net --recv-key 0x810273C4

#Make sure that dpkg is happy
dpkg --configure -a

echo -e "\nChroot: updating apt and apt-key\n"
sleep 1
apt-get update
apt-key update

# Required for add-apt-repository
echo -e "\nChroot: Installing software-properties-common\n"
apt-get install -y software-properties-common
echo -e "\nChroot: Installing python-software-properties\n"
apt-get install -y python-software-properties

echo -e "\nChroot: installing dbus\n"
sleep 1
apt-get install -y dbus

echo "Installing plymouth pakcages"
apt-get install -y plymouth-label
apt-get install -y plymouth-themes
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl

apt-get install --yes ubuntu-standard casper lupin-casper
apt-get install --yes discover laptop-detect os-prober
apt-get install --yes linux-generic
apt-get install --yes grub2 plymouth-x11
apt-get install --yes isolinux
apt-get install --yes plymouth
apt-get install --yes ubiquity
apt-get install --yes ubiquity-frontend-gtk
apt-get install --yes ubiquity-frontend-gtk-dbgsym
#Install Packages needed for the live system
echo -e "\nChroot: Installing packages for the live system\n"
sleep 1
apt-get install -y ubuntu-minimal casper lupin-casper ubiquity-casper
apt-get install -y syslinux isolinux


echo -e "\nChroot: Installing discover and os-prober\n"
sleep 1
apt-get install -y discover os-prober


echo -e "\nChroot: Installing linux-generic\n"
sleep 1
apt-get install -y linux-generic


echo -e "\nChroot: Installing grub2 and plymouth-x11\n"
sleep 1

apt-get install -y grub-pc grub-pc-bin grub2-common grub-common grub-gfxpayload-lists plymouth-x11


#Install and configure Karoshi
chmod 0755 /opt/karoshi/clientsetup/buildclient/buildclient
echo "Running buildclient"
sleep 4

cd /opt/karoshi/clientsetup/buildclient
chmod 0755 buildclient
./buildclient

cd

echo -e "\nChroot: ubiquity-frontend-gtk\n"
sleep 1
apt-get install -y ubiquity-frontend-gtk

#Add the ubuntu user for casper
#echo -e "\nChroot: Creating karoshi user\n"
#sleep 1
#useradd -u 999 -m -d /home/ubuntu ubuntu
#read pause

function disable_script {
for arg in "$@"; do
echo "Disabling $arg" >&2
dpkg-divert --local --add "$arg"
cat > "$arg" <<- EOF
#!/bin/bash
exit 0 #disabled
EOF
done
}
#Prevent CD being added as apt repository, and prevent attempted user creation
disable_script /usr/share/ubiquity/apt-setup
disable_script /usr/lib/ubiquity/user-setup/user-setup-apply
disable_script /usr/share/initramfs-tools/scripts/casper-bottom/{25adduser,41apt_cdrom}

#Chroot clean up
rm /var/lib/dbus/machine-id
[ -f /sbin/initctl ] && rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl
update in
#Remove old linux kernels if there are more than one
ls /boot/vmlinuz-3.13.**-**-generic > list.txt
sum=$(cat list.txt | grep '[^ ]' | wc -l)

if [ $sum -gt 1 ]; then
dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | xargs sudo apt-get purge
fi

#Update initramfs
update-initramfs -u

rm list.txt

apt-get clean

rm -rf /tmp/*

rm /etc/resolv.conf

umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
exit
