#!/bin/bash

mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts
export HOME=/root
export LC_ALL=C

sudo apt-get install -y software-properties-common
#Create /tmp/fake for symlinks to /bin/true
mkdir /tmp/fake

ln -s /bin/true /tmp/fake/initctl
ln -s /bin/true /tmp/fake/invoke-rc.d
ln -s /bin/true /tmp/fake/restart
ln -s /bin/true /tmp/fake/start
ln -s /bin/true /tmp/fake/stop
ln -s /bin/true /tmp/fake/start-stop-daemon
ln -s /bin/true /tmp/fake/service

export PATH=/tmp/fake:$PATH
export DEBIAN_FRONTEND=noninteractive

add-apt-repository -y ppa:otto-kesselgulasch/gimp
add-apt-repository -y ppa:libreoffice/libreoffice-5-0
add-apt-repository -y ppa:nilarimogard/webupd8
add-apt-repository -y ppa:webupd8team/atom
add-apt-repository -y ppa:ubuntu-wine/ppa
add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ saucy universe multiverse"
add-apt-repository -y ppa:xubuntu-dev/xfce-4.12
add-apt-repository -y "deb http://archive.getdeb.net/ubuntu $(lsb_release -sc)-getdeb apps"
add-apt-repository -y ppa:webupd8team/y-ppa-manager


#GPG keys
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 614C4B28
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xcbcb082a1bb943db
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -0- | apt-key add -
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1378B444
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4C9D234C
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F9CB8DB0
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 96EFFE86
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 142986CE
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
wget -qO - https://packagecloud.io/github/git-lfs/gpgkey | sudo apt-key add -

sudo apt-get update
sudo apt-key update


#Make sure that dpkg is happy
dpkg --configure -a

echo -e "\nChroot: updating apt\n"
sleep 1
apt-get update

echo -e "\nChroot: installing dbus\n"
sleep 1
apt-get install -y dbus


echo "Installing plymouth pakcages"
apt-get install -y plymouth-label
apt-get install -y plymouth-themes
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl

apt-get install --yes ubuntu-standard casper lupin-casper
apt-get install --yes discover laptop-detect os-prober
apt-get install --yes linux-generic
apt-get install --yes grub2 plymouth-x11
apt-get install --yes ubiquity-frontend-gtk
apt-get install --yes isolinux
apt-get install --yes plymouth
apt-get install --yes ubiquity
#Install Packages needed for the live system
echo -e "\nChroot: Installing packages for the live system\n"
sleep 1
apt-get install -y ubuntu-minimal casper lupin-casper ubiquity-casper
apt-get install -y syslinux isolinux


echo -e "\nChroot: Installing discover and os-prober\n"
sleep 1
apt-get install -y discover os-prober


echo -e "\nChroot: Installing linux-generic\n"
sleep 1
apt-get install -y linux-generic


echo -e "\nChroot: Installing grub2 and plymouth-x11\n"
sleep 1

apt-get install -y grub-pc grub-pc-bin grub2-common grub-common grub-gfxpayload-lists plymouth-x11

echo -e "\nChroot: Installing python-software-properties\n"
sleep 1
apt-get install -y software-properties-common python-software-properties


echo -e "\nChroot: Installing wget\n"
sleep 1
apt-get install --yes wget


apt-get update
#Install and configure Karoshi
chmod 0755 /opt/karoshi/clientsetup/buildclient/buildclient
echo "Running buildclient"
sleep 4

cd /opt/karoshi/clientsetup/buildclient
chmod 0755 buildclient
sudo ./buildclient

cd

echo -e "\nChroot: ubiquity-frontend-gtk\n"
sleep 1
apt-get install -y ubiquity-frontend-gtk

#Add the ubuntu user for casper
#echo -e "\nChroot: Creating karoshi user\n"
#sleep 1
#useradd -u 999 -m -d /home/ubuntu ubuntu
#read pause

function disable_script {
for arg in "$@"; do
echo "Disabling $arg" >&2
dpkg-divert --local --add "$arg"
cat > "$arg" <<- EOF
#!/bin/bash
exit 0 #disabled
EOF
done
}
#Prevent CD being added as apt repository, and prevent attempted user creation
disable_script /usr/share/ubiquity/apt-setup
disable_script /usr/lib/ubiquity/user-setup/user-setup-apply
disable_script /usr/share/initramfs-tools/scripts/casper-bottom/{25adduser,41apt_cdrom}

#Chroot clean up
rm /var/lib/dbus/machine-id
[ -f /sbin/initctl ] && rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl
sudo update in
#Remove old linux kernels if there are more than one
ls /boot/vmlinuz-3.13.**-**-generic > list.txt
sum=$(cat list.txt | grep '[^ ]' | wc -l)

if [ $sum -gt 1 ]; then
dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | xargs sudo apt-get purge
fi

#Update initramfs
sudo update-initramfs -u

rm list.txt

apt-get clean

rm -rf /tmp/*

rm /etc/resolv.conf

umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
exit
