#!/bin/bash

#Copyright (C) 2013 Robin McCorkell
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

#Generate auto rules for running services on privilaged ports
if iptables -n --list karoshi-auto >/dev/null 2>&1; then
	iptables -F karoshi-auto
	while read -r protocol _ _ _ bind_addr _; do
		port=${bind_addr##*:}
		if ( [[ $protocol == "tcp" ]] || [[ $protocol == "udp" ]] ) && [[ $port =~ ^[0-9]*$ ]]; then
			iptables -A karoshi-auto -p "$protocol" --dport "$port" -j ACCEPT
		else
			echo "WARNING: Unknown error auto-generating ACCEPTion" >&2
			echo "Protocol: $protocol	Bind address: $bind_addr" >&2
		fi
	done < <(ss -4tuan sport != 127.0.0.1: and sport lt :1024 | tail -n +2)
fi

