#!/bin/bash

#Copyright (C) 2014 Robin McCorkell

#This file is part of Karoshi Client.
#
#Karoshi Client is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Client is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Client.  If not, see <http://www.gnu.org/licenses/>.

PAM_SUCCESS=0 #Successful completion.
PAM_OPEN_ERR=1 #Failure when dynamically loading a service module.
PAM_SYMBOL_ERR=2 #Symbol not found in service module.
PAM_SERVICE_ERR=3 #Error in underlying service module.
PAM_SYSTEM_ERR=4 #System error.
PAM_BUF_ERR=5 #Memory buffer error.
PAM_CONV_ERR=6 #Conversation failure.
PAM_PERM_DENIED=7 #The caller does not possess the required authority.
PAM_MAXTRIES=8 #Maximum number of tries exceeded.
PAM_AUTH_ERR=9 #Authentication error.
PAM_NEW_AUTHTOK_REQD=10 #New authentication token required from user.
PAM_CRED_INSUFFICIENT=11 #Cannot access authentication database because credentials supplied are insufficient.
PAM_AUTHINFO_UNAVAIL=12 #Cannot retrieve authentication information.
PAM_USER_UNKNOWN=13 #The user is not known to the underlying account management module.
PAM_CRED_UNAVAIL=14 #Cannot retrieve user credentials.
PAM_CRED_EXPIRED=15 #User credentials have expired.
PAM_CRED_ERR=16 #Failure setting user credentials.
PAM_ACCT_EXPIRED=17 #User account has expired.
PAM_AUTHTOK_EXPIRED=18 #Password expired and no longer usable.
PAM_SESSION_ERR=19 #Cannot initiate/terminate a PAM session.
PAM_AUTHTOK_ERR=20 #Error in manipulating authentication token.
PAM_AUTHTOK_RECOVERY_ERR=21 #Old authentication token cannot be recovered.
PAM_AUTHTOK_LOCK_BUSY=22 #The authentication token lock is busy.
PAM_AUTHTOK_DISABLE_AGING=23 #Authentication token ageing is disabled.
PAM_NO_MODULE_DATA=24 #Module data not found.
PAM_IGNORE=25 #Ignore this module.
PAM_ABORT=26 #General PAM failure.
PAM_TRY_AGAIN=27 #Unable to complete operation. Try again.
PAM_MODULE_UNKNOWN=28 #Module type unknown.
PAM_DOMAIN_UNKNOWN=29

# pam_set_env <user>
function pam_set_env {
	if (( $# < 1 )); then return 1; fi
	IFS=":" read -r USER _ USER_UID USER_GID GECOS HOME SHELL < <(getent passwd "$1")
}

pam_set_env "$PAM_USER"
