#!/bin/bash

#Copyright (C) 2013 Robin McCorkell
#Original Copyright (C) 2010  Paul Sharrad

#This file is part of Karoshi Client.
#
#Karoshi Client is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Client is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Client.  If not, see <http://www.gnu.org/licenses/>.

#The Karoshi Team can be contact either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

source /opt/karoshi/linuxclientsetup/utilities/common

if [[ $EUID -ne 0 ]]; then
	echo "ERROR: Must be running as effective root" >&2
	info_alert "Privilage Error" "This script must be run as root"
	exit 1
fi

function exitfunc {
	info_alert "Change Password" "Passwords not set - original still active"
	karoshi-manage-flags set passwordset
	exit 0
}

username=karoshi

password_set=false
while ! $password_set; do
	understandableYad --title='Change Password' --form --wrap --text "Password change: $username + root" --field='Password':H --field='Confirm':H --button='gtk-cancel:1' --button='gtk-ok:0'
	password1=`cut -d"|" -f1 <<< "$DATA"`
	password2=`cut -d"|" -f2 <<< "$DATA"`
	if [[ $password1 == "$password2" ]]; then
		password_set=true
	else
		info_alert "Warning" "The passwords did not match"
	fi
done

#Change password
echo -e "$username:$password1" | chpasswd
echo -e "root:$password1" | chpasswd
karoshi-manage-flags set passwordset
#Show completed message
info_alert "Change Password" "Password changed for $username and root"
exit 0

