#!/bin/bash

#Copyright (C) 2013 Robin McCorkell
#Original Copyright (C) 2010  Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contact either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

source /opt/karoshi/linuxclientsetup/utilities/common

function exitfunc {
	info_alert "Error" "Passwords not set - original still active"
	exit $1
}

username=administrator

password_set=false
while ! $password_set; do
	understandableYad --title='Change Password' --form --wrap --text "Password change: $username + root" --field='Password':H --field='Confirm':H --button='gtk-cancel:1' --button='gtk-ok:0'
	password1=`cut -d"|" -f1 <<< "$DATA"`
	password2=`cut -d"|" -f2 <<< "$DATA"`
	if [[ $password1 == "$password2" ]]; then
		password_set=true
	else
		info_alert "Warning" "The passwords did not match"
	fi
done

#Change password
echo -e "$username:$password1" | chpasswd
echo -e "root:$password1" | chpasswd
karoshi-manage-flags set passwordset
#Show completed message
info_alert "Change Password" "Password changed for $username and root"
exit 0

