#!/bin/bash

#Copyright (C) 2013 Robin McCorkell
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

source /opt/karoshi/linuxclientsetup/utilities/common

#Exit this script if running live.
if [[ `mount | grep -c -w /cow` -gt 0 ]]
then
	exit 
fi

##################
#Logging
##################
[[ ! -d /var/log/karoshi ]] && mkdir -p /var/log/karoshi

[[ -e /var/log/karoshi ]] && rm -rf /var/log/karoshi
mkdir -p /var/log/karoshi

touch /var/log/karoshi/{pre-session,post-session,virtualbox-mkdir,setup}.log
chown root:adm /var/log/karoshi/{pre-session,post-session,virtualbox-mkdir,setup}.log
chmod 0640 /var/log/karoshi/{pre-session,post-session,virtualbox-mkdir,setup}.log

exec &>/var/log/karoshi/setup.log

#Create symlink to Karoshi update log
ln -s /var/log/upstart/karoshi-update.log /var/log/karoshi/update.log

#Allow root to connect to X even after hostname is changed (temporarily)
xhost +si:localuser:root

##################
#Configure system
##################
#Create flag directory
mkdir -p /opt/karoshi/flags

#Configure network
if ! karoshi-manage-flags get networkset || ( ! karoshi-manage-flags get domainset && ! karoshi-manage-flags get nokaroshi ); then
	karoshi-set-network
fi

#Change client password
if ! karoshi-manage-flags get passwordset; then
	karoshi-set-local-password
fi

#Configure Wireshark to allow non-root to capture packets
if [[ -e /usr/bin/dumpcap ]]; then
	groupadd --system wireshark
	chown root:wireshark /usr/bin/dumpcap
	if which setcap > /dev/null ; then
		chmod u=rwx,g=rx,o=r /usr/bin/dumpcap
		if ! setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap; then
			echo "Setting capabilities for dumpcap using Linux Capabilities failed."
			echo "Falling back to setting set-user-id bit."
			chmod u=rwxs,g=rx,o=r /usr/bin/dumpcap
		fi
	else
			chmod u=rwxs,g=rx,o=r /usr/bin/dumpcap
	fi
fi

##################
#Install Karoshi files
##################
[[ -e /etc/init/karoshi-update.conf ]] && rm -rf /etc/init/karoshi-update.conf
[[ -e /etc/init/karoshi-idle-shutdown.conf ]] && rm -rf /etc/init/karoshi-idle-shutdown.conf
cp -f /opt/karoshi/linuxclientsetup/utilities/karoshi-{update,idle-shutdown}.conf /etc/init
chmod 644 /etc/init/karoshi-{update,idle-shutdown}.conf

[[ -e /opt/karoshi/scripts ]] && rm -rf /opt/karoshi/scripts
cp -rf /opt/karoshi/linuxclientsetup/scripts /opt/karoshi
find /opt/karoshi/scripts -mindepth 1 -print0 | xargs -r0 chmod 755

[[ -e /opt/karoshi/admin-skel ]] && rm -rf /opt/karoshi/admin-skel
cp -rf /opt/karoshi/linuxclientsetup/admin-skel /opt/karoshi

[[ -e /opt/karoshi/images ]] && rm -rf /opt/karoshi/images
mkdir -p /opt/karoshi/images
cp -f /opt/karoshi/linuxclientsetup/images/{,login-}background.png /opt/karoshi/images

#Configure LightDM to use new background location
sed -i "s@^Background=.*@Background=/opt/karoshi/images/login-background.png@" /etc/lightdm/lightdm-kde-greeter.conf
#Configure XFCE to use new background location
sed -i "s@<property name=[\"']image-path[\"'] type=[\"']string[\"'] value=[\"'].*[\"']/>@<property name=\"image-path\" type=\"string\" value=\"/opt/karoshi/images/background.png\"/>" /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

#Configure Karoshi PAM modules
pam-auth-update --package --remove karoshi-pre-session karoshi-post-session karoshi-virtualbox-mkdir
pam-auth-update --package

##################
#Finish and restart
##################
#Stop Auto logon
sed -i 's/^autologin/#autologin/' /etc/lightdm/lightdm.conf
#Stop running this script on administrator login
[[ -f ~administrator/.config/autostart/karoshi-setup.desktop ]] && rm -f ~administrator/.config/autostart/karoshi-setup.desktop

shutdown -r now
exit

