#!/bin/bash

#Copyright (C) 2013 Robin McCorkell

#This file is part of Karoshi Client.
#
#Karoshi Client is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Client is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Client.  If not, see <http://www.gnu.org/licenses/>.

#The Karoshi Team can be contacted either at mpsharrad@karoshi.org.uk or rmccorkell@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

if [[ ! $PAM_USER ]]; then
	echo "ERROR: Must be run through pam_exec.so" >&2
	exit $PAM_CRED_UNAVAIL
fi
#Make sure the user exists
if ! getent passwd "$PAM_USER" >/dev/null; then
	echo "ERROR: Must be run with a valid PAM_USER" >&2
	exit $PAM_USER_UNKNOWN
fi

virtualbox_path="/opt/virtualbox"
user_info=$(getent passwd "$PAM_USER")
user_uid=$(cut -d":" -f3 <<< "$user_info")
user_gid=$(cut -d":" -f4 <<< "$user_info")
user_home=$(cut -d":" -f6 <<< "$user_info")

echo "$0 for $PAM_USER"

if ! [[ $user_uid -ge 1000 ]]; then
	echo "User is not a domain user - exiting"
	exit $PAM_IGNORE
fi

if [[ ! -d $virtualbox_path ]]; then
	echo "$virtualbox_path did not exist - creating"
	mkdir -p "$virtualbox_path" -m 0755
fi
if [[ ! -d $virtualbox_path/isos ]]; then
	echo "$virtualbox_path/isos did not exist - creating"
	mkdir "$virtualbox_path"/isos -m 1777
fi
if [[ ! -d $virtualbox_path/users ]]; then
	echo "$virtualbox_path/users did not exist - creating"
	mkdir "$virtualbox_path"/users -m 0755
fi

function make_virtualbox_dir {
	echo "Creating user folder: '$virtualbox_path/users/$PAM_USER'"
	mkdir "$virtualbox_path"/users/"$PAM_USER" -m 0700
	chown $user_uid:$user_gid "$virtualbox_path"/users/"$PAM_USER"
}

if [[ ! -d $virtualbox_path/users/$PAM_USER ]]; then
	make_virtualbox_dir
fi

folder_owner=$(stat -c %U "$virtualbox_path"/users/"$PAM_USER")
if [[ $folder_owner != $PAM_USER ]]; then
	echo "Incorrect owner of user folder: $folder_owner"
	echo "Moving '$virtualbox_path/users/$PAM_USER' to '$virtualbox_path/users/$PAM_USER.old'"
	[[ -e $virtualbox_path/users/$PAM_USER.old ]] && rm -rf "$virtualbox_path"/users/"$PAM_USER".old
	mv "$virtualbox_path"/users/"$PAM_USER" "$virtualbox_path"/users/"$PAM_USER".old
	make_virtualbox_dir
fi

if ! [[ -e $user_home/.VirtualBox ]]; then
	ln -sf "$virtualbox_path"/users/"$PAM_USER" "$user_home"/.VirtualBox
else
	echo "'$user_home/.VirtualBox' already exists! Not creating symlink"
fi
if ! [[ -e $user_home/"VirtualBox VMs" ]]; then
	ln -sf "$virtualbox_path"/users/"$PAM_USER" "$user_home"/"VirtualBox VMs"
else
	echo "'$user_home/VirtualBox VMs' already exists! Not creating symlink"
fi

exit $PAM_SUCCESS
